"""add_deleted_at_to_training_sessions

Revision ID: 557bf2b55512
Revises: c1580fd35229
Create Date: 2026-03-11 18:07:25.487620
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557bf2b55512'
down_revision: Union[str, None] = 'c1580fd35229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        'ix_training_sessions_active',
        'training_sessions',
        ['user_id', 'session_date'],
        unique=False,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_sessions_active', table_name='training_sessions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('training_sessions', 'deleted_at')
    # ### end Alembic commands ###
