"""add_core_domains_and_gamification

Revision ID: c1580fd35229
Revises: a68450dd7890
Create Date: 2026-03-09 18:00:34.569088
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1580fd35229'
down_revision: Union[str, None] = 'a68450dd7890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='achievementrarity'), server_default='common', nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trigger_key', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), server_default='New Conversation', nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_active', 'conversations', ['user_id', 'updated_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('recovery_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_for', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('energy >= 1 AND energy <= 5', name='ck_energy_log_range'),
    sa.CheckConstraint('sleep_quality >= 1 AND sleep_quality <= 5', name='ck_sleep_range'),
    sa.CheckConstraint('soreness >= 1 AND soreness <= 5', name='ck_soreness_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'logged_for', name='uq_recovery_user_date')
    )
    op.create_index('ix_recovery_logs_user_date', 'recovery_logs', ['user_id', 'logged_for'], unique=False)
    op.create_table('streak_days',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.Enum('TRAINING', 'RECOVERY', 'REST', 'MISSED', name='streakdaytype'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_streak_user_date')
    )
    op.create_index(op.f('ix_streak_days_user_id'), 'streak_days', ['user_id'], unique=False)
    op.create_table('training_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_level', sa.String(length=20), nullable=True),
    sa.Column('martial_arts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('weight_class', sa.String(length=30), nullable=True),
    sa.Column('training_frequency', sa.String(length=30), nullable=True),
    sa.Column('injuries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('role', sa.String(length=20), server_default='fighter', nullable=False),
    sa.Column('primary_domain', sa.String(length=30), nullable=True),
    sa.Column('game_style', sa.String(length=20), nullable=True),
    sa.Column('strategic_leaks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('conversation_insights', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('profile_completeness', sa.Integer(), server_default='0', nullable=False),
    sa.Column('language_code', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('weight_unit', sa.String(length=5), server_default='kg', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('grace_days_remaining', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_training_profiles_conversation_insights', 'training_profiles', ['conversation_insights'], unique=False, postgresql_using='gin')
    op.create_index('ix_training_profiles_injuries', 'training_profiles', ['injuries'], unique=False, postgresql_using='gin')
    op.create_index('ix_training_profiles_martial_arts', 'training_profiles', ['martial_arts'], unique=False, postgresql_using='gin')
    op.create_index('ix_training_profiles_strategic_leaks', 'training_profiles', ['strategic_leaks'], unique=False, postgresql_using='gin')
    op.create_table('training_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_type', sa.Enum('MUAY_THAI', 'BJJ_GI', 'BJJ_NOGI', 'BOXING', 'MMA', 'WRESTLING', 'CONDITIONING', 'STRENGTH', 'OTHER', name='sessiontype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('round_duration_minutes', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('intensity_rpe', sa.Integer(), nullable=True),
    sa.Column('mood_before', sa.Integer(), nullable=True),
    sa.Column('mood_after', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('techniques', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('training_partner', sa.String(length=100), nullable=True),
    sa.Column('gym_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'VOICE', 'AI', name='sessionsource'), server_default='manual', nullable=False),
    sa.Column('exertion_load', sa.Float(), nullable=True),
    sa.Column('session_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes < 600', name='ck_duration_range'),
    sa.CheckConstraint('energy_level >= 1 AND energy_level <= 5', name='ck_energy_range'),
    sa.CheckConstraint('intensity_rpe >= 1 AND intensity_rpe <= 10', name='ck_rpe_range'),
    sa.CheckConstraint('mood_after >= 1 AND mood_after <= 5', name='ck_mood_after_range'),
    sa.CheckConstraint('mood_before >= 1 AND mood_before <= 5', name='ck_mood_before_range'),
    sa.CheckConstraint('rounds >= 0 AND rounds <= 100', name='ck_rounds_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_sessions_techniques', 'training_sessions', ['techniques'], unique=False, postgresql_using='gin')
    op.create_index('ix_training_sessions_user_date', 'training_sessions', ['user_id', 'session_date'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_index('ix_training_sessions_user_type', 'training_sessions', ['user_id', 'session_type'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_id', sa.Uuid(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_metadata', 'messages', ['metadata'], unique=False, postgresql_using='gin')
    op.create_table('notebook_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TECHNIQUE', 'DRILL', 'GOAL', 'GEAR', 'GYM', 'INSIGHT', name='notetype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='notestatus'), server_default='active', nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.Enum('AI', 'MANUAL', name='notesource'), server_default='ai', nullable=False),
    sa.Column('source_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_entries_user_id'), 'notebook_entries', ['user_id'], unique=False)
    op.create_index('ix_notebook_entries_user_pinned', 'notebook_entries', ['user_id', 'pinned'], unique=False, postgresql_where='pinned = true')
    op.create_index('ix_notebook_entries_user_type', 'notebook_entries', ['user_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notebook_entries_user_type', table_name='notebook_entries')
    op.drop_index('ix_notebook_entries_user_pinned', table_name='notebook_entries', postgresql_where='pinned = true')
    op.drop_index(op.f('ix_notebook_entries_user_id'), table_name='notebook_entries')
    op.drop_table('notebook_entries')
    op.drop_index('ix_messages_metadata', table_name='messages', postgresql_using='gin')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_training_sessions_user_type', table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index('ix_training_sessions_user_date', table_name='training_sessions')
    op.drop_index('ix_training_sessions_techniques', table_name='training_sessions', postgresql_using='gin')
    op.drop_table('training_sessions')
    op.drop_index('ix_training_profiles_strategic_leaks', table_name='training_profiles', postgresql_using='gin')
    op.drop_index('ix_training_profiles_martial_arts', table_name='training_profiles', postgresql_using='gin')
    op.drop_index('ix_training_profiles_injuries', table_name='training_profiles', postgresql_using='gin')
    op.drop_index('ix_training_profiles_conversation_insights', table_name='training_profiles', postgresql_using='gin')
    op.drop_table('training_profiles')
    op.drop_index(op.f('ix_streak_days_user_id'), table_name='streak_days')
    op.drop_table('streak_days')
    op.drop_index('ix_recovery_logs_user_date', table_name='recovery_logs')
    op.drop_table('recovery_logs')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index('ix_conversations_user_active', table_name='conversations', postgresql_where='deleted_at IS NULL')
    op.drop_table('conversations')
    op.drop_table('achievements')
    # ### end Alembic commands ###
