"""add_performance_events_and_user_training_state

Revision ID: f8ce5b717d51
Revises: ff35c8454d97
Create Date: 2026-03-22 13:27:39.480068
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8ce5b717d51'
down_revision: Union[str, None] = 'ff35c8454d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_training_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_focus', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('active_injuries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('short_term_goals', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_training_state_user')
    )
    op.create_index('ix_training_state_focus', 'user_training_state', ['current_focus'], unique=False, postgresql_using='gin')
    op.create_index('ix_training_state_goals', 'user_training_state', ['short_term_goals'], unique=False, postgresql_using='gin')
    op.create_index('ix_training_state_injuries', 'user_training_state', ['active_injuries'], unique=False, postgresql_using='gin')
    op.create_table('performance_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('sparring', 'competition', 'drill', 'open_mat', name='eventtype'), nullable=False),
    sa.Column('discipline', sa.Enum('muay_thai', 'bjj_gi', 'bjj_nogi', 'boxing', 'mma', 'wrestling', name='discipline'), nullable=False),
    sa.Column('outcome', sa.Enum('win', 'loss', 'draw', 'no_contest', 'mixed', name='outcome'), nullable=True),
    sa.Column('finish_type', sa.String(length=100), nullable=True),
    sa.Column('root_causes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('opponent_description', sa.String(length=200), nullable=True),
    sa.Column('rpe_score', sa.Integer(), nullable=True),
    sa.Column('failure_domain', sa.Enum('technical', 'tactical', 'physical', 'mental', name='failuredomain'), nullable=True),
    sa.Column('cns_status', sa.Enum('optimal', 'sluggish', 'depleted', name='cnsstatus'), nullable=True),
    sa.Column('event_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('extraction_confidence >= 0.0 AND extraction_confidence <= 1.0', name='ck_perf_confidence_range'),
    sa.CheckConstraint('rpe_score >= 1 AND rpe_score <= 10', name='ck_perf_rpe_range'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_perf_events_highlights', 'performance_events', ['highlights'], unique=False, postgresql_using='gin')
    op.create_index('ix_perf_events_root_causes', 'performance_events', ['root_causes'], unique=False, postgresql_using='gin')
    op.create_index('ix_perf_events_user_date', 'performance_events', ['user_id', 'event_date'], unique=False)
    op.create_index('ix_perf_events_user_type', 'performance_events', ['user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_performance_events_user_id'), 'performance_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_events_user_id'), table_name='performance_events')
    op.drop_index('ix_perf_events_user_type', table_name='performance_events')
    op.drop_index('ix_perf_events_user_date', table_name='performance_events')
    op.drop_index('ix_perf_events_root_causes', table_name='performance_events', postgresql_using='gin')
    op.drop_index('ix_perf_events_highlights', table_name='performance_events', postgresql_using='gin')
    op.drop_table('performance_events')
    op.drop_index('ix_training_state_injuries', table_name='user_training_state', postgresql_using='gin')
    op.drop_index('ix_training_state_goals', table_name='user_training_state', postgresql_using='gin')
    op.drop_index('ix_training_state_focus', table_name='user_training_state', postgresql_using='gin')
    op.drop_table('user_training_state')
    # ### end Alembic commands ###
